services:
  allure:
    image: andgineer/allure
    command: /bin/sh -c "allure serve --host 0.0.0.0 -p 80 /allure-results"
    ports:
      - "8800:80"
    volumes:
      - ${PWD}/allure-results:/allure-results

  chrome:
    image: seleniarm/node-chromium
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge:4.9.1-20230508
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_SESSION_TIMEOUT=1800
      # Enable verbose logging for debugging
      - SE_OPTS=--log-level FINE

  firefox:
    image: seleniarm/node-firefox
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  hub:
    image: seleniarm/hub
    ports:
      - "4444:4444"
