# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
#
name: CI

env:
  PRIMARY_PYTHON_VERSION: '3.12'
  PRIMARY_PLATFORM: 'ubuntu-latest'
  PYTEST_CMD: >-
    python -m pytest 
    --verbose
    tests/

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  pull-requests: write
  contents: write

jobs:
  primary-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ env.PRIMARY_PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PRIMARY_PYTHON_VERSION }}

    - name: Install uv environment
      uses: andgineer/uv-venv@v1
    - name: Install dependencies
      run: uv pip install -r requirements.txt

    - name: Start SeleniumHub
      run: |
        mkdir -p allure-results
        docker compose up -d
        scripts/wait_selenium.sh

    - name: Test with pytest and Allure report
      run: "${{ env.PYTEST_CMD }} --alluredir=./allure-results"

    - name: Log on failure
      if: ${{ failure() }}
      run: |
        docker compose logs

    - name: Load Allure test report history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages-dir

    - name: Generate Allure test report
      uses: andgineer/allure-report@v3.3
      id: allure-report
      if: always()
      with:
        allure-results: allure-results
        website: gh-pages-dir
        reports-site-path: builds/tests

    - name: Publish Allure test report
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ always() && (steps.allure-report.outcome == 'success') }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ${{ steps.allure-report.outputs.reports-site }}
        destination_dir: ${{ steps.allure-report.outputs.reports-site-path }}
